### ISSUE TITLE
InvalidKeyId error when key is in pending deletion

### ISSUE THREAD

**Issue by zaro0508** [byu-oit/awsparams#35]
We have multiple KMS keys and one of the key is in a "pending deletion" state (https://pasteboard.co/Ij8dQ3g.png).  when we run awsparams with a key in this state we get an InvalidKeyId error.  We don't get this error when keys are not in this state. 

```
❯❯❯ awsparams ls --profile sandbox.cfservice -v 
Traceback (most recent call last):
  File "/Users/zaro0508/.virtualenvs/py36-sceptre-dev/bin/awsparams", line 10, in <module>
    sys.exit(main())
  File "/Users/zaro0508/.virtualenvs/py36-sceptre-dev/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/zaro0508/.virtualenvs/py36-sceptre-dev/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/zaro0508/.virtualenvs/py36-sceptre-dev/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/zaro0508/.virtualenvs/py36-sceptre-dev/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/zaro0508/.virtualenvs/py36-sceptre-dev/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/zaro0508/.virtualenvs/py36-sceptre-dev/lib/python3.6/site-packages/awsparams/cli.py", line 44, in ls
    for parm in aws_params.get_all_parameters(prefix=prefix, values=values, decryption=decryption, trim_name=False):
  File "/Users/zaro0508/.virtualenvs/py36-sceptre-dev/lib/python3.6/site-packages/awsparams/__init__.py", line 225, in get_all_parameters
    return self._get_all_prefix(prefix, values, decryption, trim)
  File "/Users/zaro0508/.virtualenvs/py36-sceptre-dev/lib/python3.6/site-packages/awsparams/__init__.py", line 116, in _get_all_prefix
    raw_parameters = self.ssm.get_parameters(Names=name_list, WithDecryption=decryption)
  File "/Users/zaro0508/.virtualenvs/py36-sceptre-dev/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/zaro0508/.virtualenvs/py36-sceptre-dev/lib/python3.6/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidKeyId: An error occurred (InvalidKeyId) when calling the GetParameters operation: arn:aws:kms:us-east-1:563295687221:key/4e85b6b8-b326-48af-a2b7-d183b6ece34f is pending deletion. (Service: AWSKMS; Status Code: 400; Error Code: KMSInvalidStateException; Request ID: 07ea69b6-ecb9-4ea0-ac98-575bef0ddd4a)
```

My Environment:
```
❯❯❯ python -V
Python 3.6.3

❯❯❯ pip freeze
awscli==1.16.176
awsparams==1.1.0
boto3==1.9.166
botocore==1.12.166
certifi==2019.3.9
Click==7.0
colorama==0.3.9
decorator==4.4.0
docutils==0.14
jcapiv1==3.1.0
Jinja2==2.10.1
jmespath==0.9.4
MarkupSafe==1.1.1
networkx==2.1
packaging==16.8
pyasn1==0.4.5
pyparsing==2.4.0
python-dateutil==2.8.0
PyYAML==5.1.1
rsa==3.4.2
s3transfer==0.2.1
sceptre==2.1.3
six==1.12.0
urllib3==1.25.3
```

**Comment by ndpete** [comment]
@zaro0508 Can you check if you have parameters encrypted with the Key that is pending deletion? At first glance I'm assuming its trying to decrypt a parameter that was encrypted with the key pending deletion. Regardless that is a less than useful error. I'll look deeper into this.

**Comment by zaro0508** [comment]
Hmm. i think what i might have done is encrypted a param with this key then switch to use a different key to encrypt a new version of the same parameter.  Do you happen to know how get info on which keys are used to encrypt which parameters, basically a mapping of keys and paramters?

**Comment by ndpete** [comment]
I'm not going to bother fixing this error message right now.
