### ISSUE TITLE
Get error "You must specify a region"

### ISSUE THREAD

**Issue by zaro0508** [byu-oit/awsparams#37]
Not sure what's going on but I am getting error "You must specify a region" when running awsparams

➜  ~ python -V
Python 3.7.3

➜  ~ pip freeze
awsparams==1.1.1
boto3==1.13.8
botocore==1.16.8
click==7.1.2
docutils==0.15.2
jmespath==0.10.0
python-dateutil==2.8.1
s3transfer==0.3.3
six==1.14.0
urllib3==1.25.9

➜  ~ awsparams ls --profile scipooldev
Traceback (most recent call last):
  File "/Users/zaro0508/.virtualenvs/py37-test1/bin/awsparams", line 8, in <module>
    sys.exit(main())
  File "/Users/zaro0508/.virtualenvs/py37-test1/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/zaro0508/.virtualenvs/py37-test1/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/zaro0508/.virtualenvs/py37-test1/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/zaro0508/.virtualenvs/py37-test1/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/zaro0508/.virtualenvs/py37-test1/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/zaro0508/.virtualenvs/py37-test1/lib/python3.7/site-packages/awsparams/cli.py", line 41, in ls
    aws_params = AWSParams(profile)
  File "/Users/zaro0508/.virtualenvs/py37-test1/lib/python3.7/site-packages/awsparams/__init__.py", line 56, in __init__
    self.ssm = session.client("ssm")
  File "/Users/zaro0508/.virtualenvs/py37-test1/lib/python3.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/Users/zaro0508/.virtualenvs/py37-test1/lib/python3.7/site-packages/botocore/session.py", line 835, in create_client
    client_config=config, api_version=api_version)
  File "/Users/zaro0508/.virtualenvs/py37-test1/lib/python3.7/site-packages/botocore/client.py", line 85, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/Users/zaro0508/.virtualenvs/py37-test1/lib/python3.7/site-packages/botocore/client.py", line 287, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/Users/zaro0508/.virtualenvs/py37-test1/lib/python3.7/site-packages/botocore/args.py", line 73, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/Users/zaro0508/.virtualenvs/py37-test1/lib/python3.7/site-packages/botocore/args.py", line 153, in compute_client_args
    s3_config=s3_config,
  File "/Users/zaro0508/.virtualenvs/py37-test1/lib/python3.7/site-packages/botocore/args.py", line 218, in _compute_endpoint_config
    return self._resolve_endpoint(**resolve_endpoint_kwargs)
  File "/Users/zaro0508/.virtualenvs/py37-test1/lib/python3.7/site-packages/botocore/args.py", line 301, in _resolve_endpoint
    service_name, region_name, endpoint_url, is_secure)
  File "/Users/zaro0508/.virtualenvs/py37-test1/lib/python3.7/site-packages/botocore/client.py", line 361, in resolve
    service_name, region_name)
  File "/Users/zaro0508/.virtualenvs/py37-test1/lib/python3.7/site-packages/botocore/regions.py", line 134, in construct_endpoint
    partition, service_name, region_name)
  File "/Users/zaro0508/.virtualenvs/py37-test1/lib/python3.7/site-packages/botocore/regions.py", line 148, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.

**Comment by zaro0508** [comment]
It looks like boto requires the region now.  It's the same with the AWS SSM CLI..

```
➜  aws ssm get-parameters --name /infra/JcConnectKey
You must specify a region. You can also configure your region by running "aws configure".
```

**Comment by zaro0508** [comment]
would appreciate a review @ndpete, awsparams is completely broken with this fix.

**Comment by ndpete** [comment]
I don't think this is anything new. I think region has been required for some time. I've always had my region set in my aws config for the profiles I'm using. Regardless having a region flag could be useful.

**Comment by zaro0508** [comment]
Ahh, I see. That make sense.  I recently cleared my ~/.aws/credentials file and replaced my entries and forgot to add default regions back into the file. thanks for the info @ndpete
